Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "loadbalancer" do |lb|
    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip: "192.168.56.10"
    lb.vm.provider("virtualbox") { |vb| vb.memory = "512"; vb.cpus = 1 }
    lb.vm.provision "shell", path: "scripts/lb.sh"
  end

  config.vm.define "web1" do |web|
    web.vm.hostname = "web1"
    web.vm.network "private_network", ip: "192.168.56.11"
    web.vm.synced_folder "./src", "/opt/birdwatcher"
    web.vm.provider("virtualbox") { |vb| vb.memory = "1024"; vb.cpus = 1 }
    web.vm.provision "shell", path: "scripts/web.sh"
  end

  config.vm.define "web2" do |web|
    web.vm.hostname = "web2"
    web.vm.network "private_network", ip: "192.168.56.12"
    web.vm.synced_folder "./src", "/opt/birdwatcher"
    web.vm.provider("virtualbox") { |vb| vb.memory = "1024"; vb.cpus = 1 }
    web.vm.provision "shell", path: "scripts/web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.13"
    db.vm.provider("virtualbox") { |vb| vb.memory = "1024"; vb.cpus = 1 }
    db.vm.provision "shell", path: "scripts/db.sh"
  end
end