---
- hosts: all
  become: true

  tasks:

   - name: Ensure correct configuration for VM
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
       state: present
     loop:
         - regexp: '^#*PasswordAuthentication.*'
           line: 'PasswordAuthentication no'
         - regexp: '^#*PermitEmptyPasswords.*'
           line: 'PermitEmptyPasswords no'
         - regexp: '^#*PubkeyAuthentication.*'
           line: 'PubkeyAuthentication yes'
         - regexp: '^#*PermitRootLogin.*'
           line: 'PermitRootLogin no'
     notify: Restart SSH

   - name: install trivy
     ansible.builtin.shell: |
       curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
     args:
       creates: /usr/local/bin/trivy
   - name: create trivy directory
     ansible,builtin.file:
       path: /var/log/trivy
       state: directory
       mode: "0755"
   - name: Run trivy scan regularly
     ansible.builtin.cron:
       name: "Run trivy scan"
       minute: "0"
       hour: "1"
       user: root
       job: >
         trivy fs
         --severity HIGH,CRITICAL
         --timeout 10m
         --format table
         --output "/var/log/trivy/$(hostname)_trivy_scan_$(date +\%Y\%m\%d_\%H\%M).txt"
         /
   - name: Add ssh keys for the entire team
     ansible.posix.authorized_key:
       user: "{{ item.user }}"
       state: present
       key: "{{ item.key }}"
     loop:
       - {user: vagrant, key: "{{ lookup('file', './bohdan.pub') }}"}
       - {user: vagrant, key: "{{ lookup('file', './bozhena.pub') }}"}
       - {user: vagrant, key: "{{ lookup('file', './maksym.pub') }}"}
       - {user: vagrant, key: "{{ lookup('file', './marta.pub') }}"}
       - {user: vagrant, key: "{{ lookup('file', './anastasiya.pub') }}"}

  handlers:
   - name: Restart SSH
     ansible.builtin.service:
       name: ssh
       state: restarted
