upstream app {
    server 192.168.56.11:5000 weight=2 fail_timeout=11s;
    server 192.168.56.12:5000 weight=2 fail_timeout=11s;
}

server {
    listen 80;
    server_name 192.168.56.10;

    access_log /var/log/nginx/app-access.log;
    error_log /var/log/nginx/app-error.log;

    location / {
        proxy_pass http://app/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
